backend:
  name: git-gateway
  branch: master
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "web-hw"
    label: "Web Homework"
    folder: "src/web-hw"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Header"
        name: "header"
        widget: "string"
      - label: "Due Date"
        name: "due"
        widget: "string"
      - label: "Introduction"
        name: "introduction"
        widget: "markdown"
      - label: "Set-up"
        name: "setup"
        widget: "markdown"
      - label: "Skeleton Repo"
        name: "skeleton"
        widget: "string"
      - label: "Sections"
        name: "Sections"
        widget: "list"
        types: 
            - name: "Part Header Section"
              widget: "object"
              field: { name: Part Header, widget: string}
            - name: "Paragraph Section"
              widget: "object"
              field: { name: Paragraph, widget: markdown } 
            - name: "Code Block Section"
              widget: "object"
              field: { name: Code Block, widget: code }
            - name: "Test"
              widget: "string"
