backend:
  name: git-gateway
  branch: master
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "web-hw"
    label: "Web Homework"
    folder: "src/web-hw"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Header"
        name: "header"
        widget: "string"
      - label: "Due Date"
        name: "due"
        widget: "string"
      - label: "Introduction"
        name: "introduction"
        widget: "markdown"
      - label: "Set-up"
        name: "setup"
        widget: "markdown"
      - label: "Skeleton Repo"
        name: "skeleton"
        widget: "string"
      - label: "Content"
        name: "content"
        widget: "list"
        fields: 
          - { 
              label: "Part Headers",
              name: "subheaders", 
              widget: "list",
              field: { label: "Part Header", name: "subheader", widget: "string" }
            } 
          - { 
              label: "Paragraphs", 
              name: "paragraphs", 
              widget: "list",
              field: { label: "Paragraph", name: "paragraph", widget: "markdown"} 
            } 
          - { 
              label: "Code Blocks", 
              name: "codeblocks", 
              widget: "list",
              field: { label: "Code Block", name: "codeblock", widget: "code", output_code_only: false} 
            }
